services:

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      # - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      # - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - prometheus

  k6:
    image: grafana/k6
    container_name: k6
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./k6_scripts:/scripts

  influxdb:
    # image: influxdb:2.7.1
    image: influxdb:1.8.10
    container_name: influxdb
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_MAX_BODY_SIZE=0
      # - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      # - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    ports:
      - 8086:8086
    volumes:
      - ./data/influxdb:/var/lib/influxdb

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
     - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'    
    networks:
      - my-net

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - '9100:9100'

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-exporter
    ports:
      - '9121:9121'
    environment:
      REDIS_ADDR: "redis:6379"
      REDIS_USER: null
      REDIS_PASSWORD: password
    # links:
    #   - redis
    #   - prometheus
    depends_on:
      - redis
    networks:
      - my-net

  redis:
    build: ./redis
    container_name: redis
    # command: redis-server /redis.conf
    # environment:
    #   REDIS_PASSWORD: 
    #   REDIS_TLS_ENABLED: "yes"
    #   REDIS_TLS_CERT_FILE: /usr/local/etc/redis/redis.crt
    #   REDIS_TLS_KEY_FILE: /usr/local/etc/redis/redis.key
    #   REDIS_TLS_CA_FILE: /usr/local/etc/redis/ca.crt
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    networks:
      - my-net

  blackbox-exporter:
    image: prom/blackbox-exporter
    container_name: blackbox-exporter
    ports:
      - 9115:9115

  go-app:
    build: ./go-app
    container_name: go-api
    restart: unless-stopped
    ports:
      - 8009:8009
      - 8010:8010

networks:
  my-net:
    driver: bridge