apiVersion: v1
kind: Service
metadata:
  name: go-api-service
  labels:
    job: node-api
    app: service-api
spec:
  #type: NodePort
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    #nodePort: 30033
    protocol: TCP
    name: http
  - port: 8081
    targetPort: metrics
    #nodePort: 30034
    protocol: TCP
    name: http-metrics
  selector:
    app: go-api