apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: redis
 labels:
    app: redis
spec:
 serviceName: "redis"
 replicas: 2
 selector:
   matchLabels:
     app: redis
 template:
   metadata:
     labels:
       app: redis
   spec:
     containers:
     - name: redis
       image: redis:latest
       ports:
       - containerPort: 6379
         name: redis-port
       volumeMounts:
       - name: data
         mountPath: /data
     - name: redis-exporter
       image: oliver006/redis_exporter
       ports:
       - containerPort: 9121
         name: exporter-port
       volumeMounts:
       - name: data
         mountPath: /data
 volumeClaimTemplates:
 - metadata:
     name: data
   spec:
     accessModes: [ "ReadWriteOnce" ]
     resources:
       requests:
         storage: 1Gi