apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: go-api-service-monitor
  namespace: monitoring
  labels:
    release: prometheus # Matches kube-prometheus-stack release label
    app: prometheus
spec:
  jobLabel: job
  endpoints:
  - port: http-metrics
    interval: 15s
    scrapeTimeout: 15s
    # path: /api-path/metrics  
  namespaceSelector:
    matchNames:
      - production
  selector:
    matchLabels:
      app: service-api